### ISSUE TITLE
Cursor Color?

### ISSUE THREAD

**Issue by JCODEPENG** [jstejada/react-typist#97]
Is there a way to change the cursor color using css and assigning the className to the <Typist> tag?

**Comment by DarthBenro008** [comment]
You can simply override the SCSS in your Stylesheet.

Example: Adding the following snippet in your style sheet would update the color of the cursor to blue.
```css
.Typist .Cursor {
  color: #00a2cf !important;
}
```
